import { Inter, Noto_Sans_Georgian } from "next/font/google";
import "./globals.css";



const inter = Inter({ subsets: ["latin"] });
const defaultFont = Noto_Sans_Georgian({ subsets: ["latin"] });
export const metadata = {
  title: "Todovex",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  return (

    <html lang="en">
      <body className={defaultFont.className}>{children}</body>
    </html>

  );
}
