
import Provider from "@/components/provider/Provider";
import { authOptions, getAuthSession } from "@/utils/auth";
import { getServerSession } from "next-auth";



export const metadata = {
    title: "Loggedin page",
    description: "Generated by create next app",
};
export default async function LoggedInLayout({ children }) {
    try {
        const { session } = await getServerSession(authOptions);
        console.log("loggedin layout Session:", session); // Log session to check its value
        return (
            <Provider session={session} >
                {children}
            </Provider>
        );
    } catch (error) {
        console.error("Error fetching session:", error);
        // Handle error gracefully, such as redirecting to login page
        return <div>Error fetching session. Please log in again.</div>;
    }
}
