import Provider from "@/components/provider/Provider";
import { getAuthSession } from "@/utils/auth";


export const metadata = {
    title: "Loggedin page",
    description: "Generated by create next app",
};

export default async function LoggedInLayout({ children }) {
    const { session } = await getAuthSession()
    return (
        <Provider session={session} >
            {children}
        </Provider>
    );
}
